const mockData = [{ "id": 1, "first_name": "Jessie", "last_name": "Chaise", "email": "jchaise0@biblegateway.com", "gender": "Female" },
{ "id": 2, "first_name": "Dee dee", "last_name": "Tapply", "email": "dtapply1@reddit.com", "gender": "Female" },
{ "id": 3, "first_name": "Kariotta", "last_name": "Appleby", "email": "kappleby2@digg.com", "gender": "Female" },
{ "id": 4, "first_name": "Ilse", "last_name": "Morlon", "email": "imorlon3@typepad.com", "gender": "Female" },
{ "id": 5, "first_name": "Mellisa", "last_name": "Berrigan", "email": "mberrigan4@msn.com", "gender": "Female" },
{ "id": 6, "first_name": "Nolan", "last_name": "Pile", "email": "npile5@jimdo.com", "gender": "Male" },
{ "id": 7, "first_name": "Job", "last_name": "Hawse", "email": "jhawse6@dagondesign.com", "gender": "Male" },
{ "id": 8, "first_name": "Free", "last_name": "Newlands", "email": "fnewlands7@imageshack.us", "gender": "Male" },
{ "id": 9, "first_name": "Valentijn", "last_name": "Wraxall", "email": "vwraxall8@reddit.com", "gender": "Male" },
{ "id": 10, "first_name": "Peadar", "last_name": "Medlar", "email": "pmedlar9@phpbb.com", "gender": "Male" }]

console.log(mockData)

const participantsContainer = document.querySelector('#participants-container')


for (let i = 0; i < mockData.length; i++) {
  const newParticipant = document.createElement('div')
  newParticipant.classList.add('participant')
  participantsContainer.append(newParticipant)
  newParticipant.innerText = 
  `Name: ${mockData[i].first_name} ${mockData[i].last_name}
  Email: ${mockData[i].email}
  Gender: ${mockData[i].gender}`
}

const newDate = document.querySelector('#dateNow')

// My Solution
setInterval(function() {
  newDate.innerText = new Date()
}, 1000);


const time = document.getElementById('time')
const date = document.getElementById('date')

const formatTime = (date) => {
  // Convert getHours() result to 12 hour format
  const hours = date.getHours() % 12 || 12
  //get minutes
  const minutes = date.getMinutes()
  // check if AM or PM
  const am = date.getHours() < 12
  // PADSTART adds a zero to the number if its 1 digit
  return `${hours.toString().padStart(2, "0")}:${minutes.toString().padStart(2, "0")} ${am ? 'AM':'PM'}`
}

// Formatting the date and months into strings by using arrays
// Each array item index matches the number generated by the date method
const formatDate = (date) => {
  const DAYS = [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday"
  ]
  const MONTHS = [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
  ]

  // Returning the formatted data
  // E.g. "Monday 01 January 2023"
  return `${DAYS[date.getDay()]} ${date.getDate()} ${MONTHS[date.getMonth()]}
  ${date.getFullYear()}`
}

// Using setinterval() to check for date and time every 200 milliseconds
setInterval(() => {
  const now = new Date()
  // Setting date and time to output elements
  time.textContent = formatTime(now)
  date.textContent = formatDate(now)

}, 200)