-- Day4CreateCompany SCHEMA

CREATE DATABASE Company; -- Create database first
USE Company;

-- CREATE EMPLOYEE TABLE
CREATE TABLE Employee (Fname VARCHAR(15) NOT NULL, Lname VARCHAR(15) NOT NULL, Ssn INT NOT NULL PRIMARY KEY,
BDate DATE DEFAULT NULL, Address VARCHAR(30) DEFAULT NULL, Sex ENUM('M', 'F') DEFAULT NULL, 
Salary DOUBLE(7,2) DEFAULT NULL, SuperSsn INT DEFAULT NULL, Dno INT DEFAULT NULL);
DESCRIBE Employee;

CREATE TABLE Depertment (Dname VARCHAR(20) NOT NULL, Dnumber INT NOT NULL PRIMARY KEY, 
MgrSsn INT DEFAULT NULL, MgrStartDate DATE DEFAULT NULL);

-- INSERT INTO Depertment (DNAME, DNUMBER, MGRSSN, MGSSTARTDATE)
-- VALUES 

CREATE TABLE Dept_Locations (Dnumber INT NOT NULL, Dlocation VARCHAR(20) NOT NULL, PRIMARY KEY(Dnumber, Dlocation));

CREATE TABLE Project (Pname VARCHAR(20) NOT NULL, Pnumber INT PRIMARY KEY, Plocation VARCHAR(15) DEFAULT NULL, Dnum INT);

CREATE TABLE Works_On (Essn INT, Pno INT, Hours DECIMAL (5,5), PRIMARY KEY(Essn, Pno));

ALTER TABLE Employee ADD FOREIGN KEY (SUPERSSN) REFERENCES Employee (Ssn);
ALTER TABLE Employee ADD FOREIGN KEY (Dno) REFERENCES Depertment (Dnumber);
ALTER TABLE Depertment ADD FOREIGN KEY (MgrSsn) REFERENCES Employee (Ssn);
ALTER TABLE DEPT_LOCATIONS ADD FOREIGN KEY (Dnumber) REFERENCES Depertment (Dnumber);
ALTER TABLE Project ADD FOREIGN KEY (Dnum) REFERENCES Depertment (Dnumber);
ALTER TABLE Works_On ADD FOREIGN KEY (Essn) REFERENCES Employee (Ssn);
ALTER TABLE Works_on ADD FOREIGN KEY (Pno) REFERENCES Project (Pnumber);

CREATE TABLE Dependent (Essn INT, DependentName VARCHAR(15), Sex ENUM('M', 'F') DEFAULT NULL, 
Bdate DATE DEFAULT NULL, Relationship VARCHAR(20) DEFAULT NULL, PRIMARY KEY(Essn, DependentName));

ALTER TABLE Dependent ADD FOREIGN KEY (Essn) REFERENCES Employee (Ssn);


SELECT * FROM EMPLOYEE;
