-- LIST ALL THE AVAILABLE DATABASES.
-- SHOW DATABASES;

-- CREATE 2 DATABASES WITH NAME TEST1 AND TEST2
-- CREATE DATABASE TEST1;
-- CREATE DATABASE TEST2;

-- DELETE THE TEST2 DATABASE
-- DROP DATABASE TEST2;

-- LIST ALL THE AVAILABEL TABLES IN TEST1 DATABASE
-- USE Test1;
-- SHOW TABLES;
-- CREATE A 'LEARNER' TABLE IN TEST1 DATABASE (DB SHOULD HAVE ID, FIRSTNAME, LASTNAME, DOB, AGE COLUMNS)
-- CREATE TABLE learner (id INTEGER, first_name VARCHAR(20), last_name VARCHAR(20), dob DATE, age INTEGER);

-- -- SHOW THE DEFINITION OF THE LEARNER TABLE
-- DESCRIBE learner;