// Store elements from HTML
const timeOutput = document.getElementById('time')
const dateOutput = document.getElementById('date')

// Function to format our time
const formatTime = (date) => {
    // convert getHours() result to 12hr format
    const hours = date.getHours() % 12 || 12
    // get minutes
    const minutes = date.getMinutes()
    // Check if AM or PM
    const am = date.getHours() < 12
    // Return the time string and add AM or PM depending on the time
    return `${hours.toString().padStart(2, "0")}:${minutes.toString()
        .padStart(2, "0")} ${am ? "AM" : "PM"}`
}

// Formatting the date and months into strings by using arrays
// Each array item index matches the number generated by the date method
const formatDate = (date) => {
    const DAYS = [
        "Sunday",
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday"
    ]
    const MONTHS = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
    ]

    // Returning the formatted data
    // E.g. "Monday 01 January 2023"
    return `${DAYS[date.getDay()]} ${date.getDate()} ${MONTHS[date.getMonth()]}
    ${date.getFullYear()}`
}

// Using setinterval() to check for date and time every 200 milliseconds
setInterval(() => {
    const now = new Date()
    // Setting date and time to output elements
    timeOutput.textContent = formatTime(now)
    dateOutput.textContent = formatDate(now)

}, 200)